services:
  swarmvip:
    image: localhost/keepalived:latest
    privileged: true
    cap_add:
      - "NET_RAW"
      - "NET_ADMIN"
      - "NET_BROADCAST"
    environment:
      - SWARMVIP_INTERFACE=eth0
      - SWARMVIP_SLOT={{.Task.Slot}}
      - SWARMVIP_ADDRESSES=10.130.0.33
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

networks:
  host:
    name: host
    external: true
