#!/bin/bash -e

echo "Waiting config file /etc/keepalived/keepalived.conf"
while [ ! -e "/etc/keepalived/keepalived.conf" ]
do
  echo -n "."
  sleep 0.1
done
echo "ok"

exec keepalived -f /etc/keepalived/keepalived.conf --no-syslog --log-console --log-detail
